package com.args;

import com.common.Annotation;

import java.io.Serializable;

public class CountPatternArgs implements Serializable {
    @Annotation(value = "input file(s),mhap.gz format,generated by mHapTools and indexed")
    public String mhapPath = "";
    @Annotation("genomic CpG file, gz format and Indexed")
    public String cpgPath = "";
    @Annotation("forward primer region, in the format of chr:start-end")
    public String FPrimer = "";
    @Annotation("reverse primer region, in the format of chr:start-end")
    public String RPrimer = "";
    @Annotation("forward primer cpg pattern, in the format of mhap")
    public String FPattern = "";
    @Annotation("reverse primer cpg pattern, in the format of mhap")
    public String RPattern = "";
    @Annotation("a bed file, in the format of \"FPrimer\\tRPrimer\\\tFPattern\\\tRPattern\"")
    public String bedPath = "";
    @Annotation("output directory, created in advance")
    public String outputDir = "";
    @Annotation("prefix of the output file(s)")
    public String tag = "listPattern.out";

    public String getMhapPath() {
        return mhapPath;
    }

    public void setMhapPath(String mhapPath) {
        this.mhapPath = mhapPath;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getFPrimer() {
        return FPrimer;
    }

    public void setFPrimer(String FPrimer) {
        this.FPrimer = FPrimer;
    }

    public String getRPrimer() {
        return RPrimer;
    }

    public void setRPrimer(String RPrimer) {
        this.RPrimer = RPrimer;
    }

    public String getFPattern() {
        return FPattern;
    }

    public void setFPattern(String FPattern) {
        this.FPattern = FPattern;
    }

    public String getRPattern() {
        return RPattern;
    }

    public void setRPattern(String RPattern) {
        this.RPattern = RPattern;
    }

    public String getBedPath() {
        return bedPath;
    }

    public void setBedPath(String bedPath) {
        this.bedPath = bedPath;
    }

    public String getOutputDir() {
        return outputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

}
