package com.args;

import com.common.Annotation;

import java.io.Serializable;

public class SearchPrimerArgs implements Serializable {
    @Annotation("input tumor file,mhap.gz format,generated by mHapTools and indexed")
    public String mhapPathT = "";
    @Annotation("input normal file,mhap.gz format,generated by mHapTools and indexed")
    public String mhapPathN = "";
    @Annotation("genomic CpG file, gz format and Indexed")
    public String cpgPath = "";
    @Annotation("one region, in the format of chr:start-end")
    public String region = "";
    @Annotation("input BED file")
    public String bedPath = "";
    @Annotation("output directory, created in advance")
    public String outputDir = "";
    @Annotation(" prefix of the output file(s) [searchPrimer.out]")
    public String tag = "searchPrimer.out";
    @Annotation("fLength")
    public Integer fLength = 25;
    @Annotation("rLength")
    public Integer rLength = 25;
    @Annotation("minT")
    public Double minT = 0.1;
    @Annotation("maxN")
    public Double maxN = 0.05;
    @Annotation("minFC")
    public Double minFC = 2.0;
    @Annotation("minInsertSize")
    public Integer minInsertSize = 40;
    @Annotation("maxInsertSize")
    public Integer maxInsertSize = 160;
    @Annotation("minCov")
    public Integer minCov = 4;

    public String getMhapPathT() {
        return mhapPathT;
    }

    public void setMhapPathT(String mhapPathT) {
        this.mhapPathT = mhapPathT;
    }

    public String getMhapPathN() {
        return mhapPathN;
    }

    public void setMhapPathN(String mhapPathN) {
        this.mhapPathN = mhapPathN;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getBedPath() {
        return bedPath;
    }

    public void setBedPath(String bedPath) {
        this.bedPath = bedPath;
    }

    public String getOutputDir() {
        return outputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Integer getfLength() {
        return fLength;
    }

    public void setfLength(Integer fLength) {
        this.fLength = fLength;
    }

    public Integer getrLength() {
        return rLength;
    }

    public void setrLength(Integer rLength) {
        this.rLength = rLength;
    }

    public Double getMinT() {
        return minT;
    }

    public void setMinT(Double minT) {
        this.minT = minT;
    }

    public Double getMaxN() {
        return maxN;
    }

    public void setMaxN(Double maxN) {
        this.maxN = maxN;
    }

    public Double getMinFC() {
        return minFC;
    }

    public void setMinFC(Double minFC) {
        this.minFC = minFC;
    }

    public Integer getMinInsertSize() {
        return minInsertSize;
    }

    public void setMinInsertSize(Integer minInsertSize) {
        this.minInsertSize = minInsertSize;
    }

    public Integer getMaxInsertSize() {
        return maxInsertSize;
    }

    public void setMaxInsertSize(Integer maxInsertSize) {
        this.maxInsertSize = maxInsertSize;
    }

    public Integer getMinCov() {
        return minCov;
    }

    public void setMinCov(Integer minCov) {
        this.minCov = minCov;
    }
}
